# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = ["//vendor/ayn:__subpackages__"])

alias(
    name = "kernel",
    actual = "//vendor/ayn/kernel:kernel_aarch64",
)

# Backlights
ddk_module(
    name = "odin2mini-backlight",
    srcs = ["drivers/video/backlight/odin2mini-backlight.c"],
    out = "odin2mini-backlight.ko",
    kernel_build = ":kernel",
)


# Panels
ddk_module(
    name = "panel-synaptics-td4328",
    srcs = ["drivers/gpu/drm/panel/panel-synaptics-td4328.c"],
    out = "panel-synaptics-td4328.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-xiamen-xm91080",
    srcs = ["drivers/gpu/drm/panel/panel-xiamen-xm91080.c"],
    out = "panel-xiamen-xm91080.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-chipone-icna35xx",
    srcs = [
        "drivers/gpu/drm/panel/drm_helper_shim.c",
        "drivers/gpu/drm/panel/panel-chipone-icna35xx.c",
    ],
    out = "panel-chipone-icna35xx.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-chipwealth-ch13726a",
    srcs = ["drivers/gpu/drm/panel/panel-chipwealth-ch13726a.c"],
    out = "panel-chipwealth-ch13726a.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-ilitek-ili7836a",
    srcs = ["drivers/gpu/drm/panel/panel-ilitek-ili7836a.c"],
    out = "panel-ilitek-ili7836a.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-visionox-vtdr6130",
    srcs = [
        "drivers/gpu/drm/panel/drm_helper_shim.c",
        "drivers/gpu/drm/panel/panel-visionox-vtdr6130.c",
    ],
    out = "panel-visionox-vtdr6130.ko",
    kernel_build = ":kernel",
)
