# SPDX-License-Identifier: GPL-2.0-or-later

load("//build/kernel/kleaf:kernel.bzl", "ddk_module")

package(default_visibility = ["//vendor/ayn:__subpackages__"])

alias(
    name = "kernel",
    actual = "//vendor/ayn/kernel:kernel_aarch64",
)

# Panels
ddk_module(
    name = "panel-synaptics-td4328",
    srcs = ["drivers/gpu/drm/panel/panel-synaptics-td4328.c"],
    out = "panel-synaptics-td4328.ko",
    kernel_build = ":kernel",
)

ddk_module(
    name = "panel-xiamen-xm91080",
    srcs = ["drivers/gpu/drm/panel/panel-xiamen-xm91080.c"],
    out = "panel-xiamen-xm91080.ko",
    kernel_build = ":kernel",
)
